<a href="https://colab.research.google.com/github/Arnabsaha6/Machine-Learning/blob/master/Machine_Learning_Hands_on_CoVid_19.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
%%html 
<iframe src="https://covid.raredigitalsolutions.com" width=100% height="419px" title="Covid Rt India" ></iframe>

In [2]:
import pandas as pd

source = pd.read_csv('https://api.covid19india.org/csv/latest/state_wise_daily.csv')
source

          Date     Status     TT  AN     AP  AR  ...    TG   TR    UP   UT    WB  UN
0    14-Mar-20  Confirmed     81   0      1   0  ...     1    0    12    0     0   0
1    14-Mar-20  Recovered      9   0      0   0  ...     0    0     4    0     0   0
2    14-Mar-20   Deceased      2   0      0   0  ...     0    0     0    0     0   0
3    15-Mar-20  Confirmed     27   0      0   0  ...     2    0     1    0     0   0
4    15-Mar-20  Recovered      4   0      0   0  ...     1    0     0    0     0   0
..         ...        ...    ...  ..    ...  ..  ...   ...  ...   ...  ...   ...  ..
418  31-Jul-20  Recovered  36554  13   3840  91  ...   816  365  2060  172  2118   0
419  31-Jul-20   Deceased    764   2     68   0  ...    14    0    43    4    45   0
420  01-Aug-20  Confirmed  55117  88   9276  83  ...  2083  252  3587  264  2589   0
421  01-Aug-20  Recovered  51368  12  12750  51  ...  1114  136  2471  162  2143   0
422  01-Aug-20   Deceased    854   2     58   0  ...    11    2    47    3    48   0

[423 rows x 41 columns]

In [3]:
source.head(15)

         Date     Status  TT  AN  AP  AR  AS  ...  TN  TG  TR  UP  UT  WB  UN
0   14-Mar-20  Confirmed  81   0   1   0   0  ...   1   1   0  12   0   0   0
1   14-Mar-20  Recovered   9   0   0   0   0  ...   0   0   0   4   0   0   0
2   14-Mar-20   Deceased   2   0   0   0   0  ...   0   0   0   0   0   0   0
3   15-Mar-20  Confirmed  27   0   0   0   0  ...   0   2   0   1   0   0   0
4   15-Mar-20  Recovered   4   0   0   0   0  ...   0   1   0   0   0   0   0
5   15-Mar-20   Deceased   0   0   0   0   0  ...   0   0   0   0   0   0   0
6   16-Mar-20  Confirmed  15   0   0   0   0  ...   0   1   0   0   1   0   0
7   16-Mar-20  Recovered   1   0   0   0   0  ...   1   0   0   0   0   0   0
8   16-Mar-20   Deceased   0   0   0   0   0  ...   0   0   0   0   0   0   0
9   17-Mar-20  Confirmed  11   0   0   0   0  ...   0   1   0   2   0   1   0
10  17-Mar-20  Recovered   1   0   0   0   0  ...   0   0   0   1   0   0   0
11  17-Mar-20   Deceased   1   0   0   0   0  ...   0   0   0   0   0   0   0
12  18-Mar-20  Confirmed  37   0   0   0   0  ...   1   8   0   2   1   0   0
13  18-Mar-20  Recovered   0   0   0   0   0  ...   0   0   0   0   0   0   0
14  18-Mar-20   Deceased   0   0   0   0   0  ...   0   0   0   0   0   0   0

[15 rows x 41 columns]

In [4]:
source.tail(15)

          Date     Status     TT  AN     AP  ...   TR    UP   UT    WB  UN
408  28-Jul-20  Confirmed  49631  25   7948  ...  221  3458  259  2134   0
409  28-Jul-20  Recovered  35683   4   3064  ...  154  1687   45  2105   0
410  28-Jul-20   Deceased    774   0     58  ...    4    41    4    38   0
411  29-Jul-20  Confirmed  52479  65  10093  ...  216  3383  279  2294   0
412  29-Jul-20  Recovered  32886   5   2784  ...   57  1287   91  2094   0
413  29-Jul-20   Deceased    775   1     65  ...    0    33    2    41   0
414  30-Jul-20  Confirmed  54968  42  10167  ...  219  3705  199  2434   0
415  30-Jul-20  Recovered  37425   0   4618  ...  284   996  185  2140   0
416  30-Jul-20   Deceased    784   1     68  ...    0    57    4    46   0
417  31-Jul-20  Confirmed  57486  78  10376  ...  274  4422  118  2496   0
418  31-Jul-20  Recovered  36554  13   3840  ...  365  2060  172  2118   0
419  31-Jul-20   Deceased    764   2     68  ...    0    43    4    45   0
420  01-Aug-20  Confirmed  55117  88   9276  ...  252  3587  264  2589   0
421  01-Aug-20  Recovered  51368  12  12750  ...  136  2471  162  2143   0
422  01-Aug-20   Deceased    854   2     58  ...    2    47    3    48   0

[15 rows x 41 columns]

In [5]:
source[:10]

        Date     Status  TT  AN  AP  AR  AS  BR  ...  SK  TN  TG  TR  UP  UT  WB  UN
0  14-Mar-20  Confirmed  81   0   1   0   0   0  ...   0   1   1   0  12   0   0   0
1  14-Mar-20  Recovered   9   0   0   0   0   0  ...   0   0   0   0   4   0   0   0
2  14-Mar-20   Deceased   2   0   0   0   0   0  ...   0   0   0   0   0   0   0   0
3  15-Mar-20  Confirmed  27   0   0   0   0   0  ...   0   0   2   0   1   0   0   0
4  15-Mar-20  Recovered   4   0   0   0   0   0  ...   0   0   1   0   0   0   0   0
5  15-Mar-20   Deceased   0   0   0   0   0   0  ...   0   0   0   0   0   0   0   0
6  16-Mar-20  Confirmed  15   0   0   0   0   0  ...   0   0   1   0   0   1   0   0
7  16-Mar-20  Recovered   1   0   0   0   0   0  ...   0   1   0   0   0   0   0   0
8  16-Mar-20   Deceased   0   0   0   0   0   0  ...   0   0   0   0   0   0   0   0
9  17-Mar-20  Confirmed  11   0   0   0   0   0  ...   0   0   1   0   2   0   1   0

[10 rows x 41 columns]

In [6]:
source[::3]

          Date     Status     TT  AN     AP  ...   TR    UP   UT    WB  UN
0    14-Mar-20  Confirmed     81   0      1  ...    0    12    0     0   0
3    15-Mar-20  Confirmed     27   0      0  ...    0     1    0     0   0
6    16-Mar-20  Confirmed     15   0      0  ...    0     0    1     0   0
9    17-Mar-20  Confirmed     11   0      0  ...    0     2    0     1   0
12   18-Mar-20  Confirmed     37   0      0  ...    0     2    1     0   0
..         ...        ...    ...  ..    ...  ...  ...   ...  ...   ...  ..
408  28-Jul-20  Confirmed  49631  25   7948  ...  221  3458  259  2134   0
411  29-Jul-20  Confirmed  52479  65  10093  ...  216  3383  279  2294   0
414  30-Jul-20  Confirmed  54968  42  10167  ...  219  3705  199  2434   0
417  31-Jul-20  Confirmed  57486  78  10376  ...  274  4422  118  2496   0
420  01-Aug-20  Confirmed  55117  88   9276  ...  252  3587  264  2589   0

[141 rows x 41 columns]

In [7]:
source[source.Status == 'Confirmed']

          Date     Status     TT  AN     AP  ...   TR    UP   UT    WB  UN
0    14-Mar-20  Confirmed     81   0      1  ...    0    12    0     0   0
3    15-Mar-20  Confirmed     27   0      0  ...    0     1    0     0   0
6    16-Mar-20  Confirmed     15   0      0  ...    0     0    1     0   0
9    17-Mar-20  Confirmed     11   0      0  ...    0     2    0     1   0
12   18-Mar-20  Confirmed     37   0      0  ...    0     2    1     0   0
..         ...        ...    ...  ..    ...  ...  ...   ...  ...   ...  ..
408  28-Jul-20  Confirmed  49631  25   7948  ...  221  3458  259  2134   0
411  29-Jul-20  Confirmed  52479  65  10093  ...  216  3383  279  2294   0
414  30-Jul-20  Confirmed  54968  42  10167  ...  219  3705  199  2434   0
417  31-Jul-20  Confirmed  57486  78  10376  ...  274  4422  118  2496   0
420  01-Aug-20  Confirmed  55117  88   9276  ...  252  3587  264  2589   0

[141 rows x 41 columns]

In [8]:
source.iloc[2]

Date      14-Mar-20
Status     Deceased
TT                2
AN                0
AP                0
AR                0
AS                0
BR                0
CH                0
CT                0
DN                0
DD                0
DL                1
GA                0
GJ                0
HR                0
HP                0
JK                0
JH                0
KA                1
KL                0
LA                0
LD                0
MP                0
MH                0
MN                0
ML                0
MZ                0
NL                0
OR                0
PY                0
PB                0
RJ                0
SK                0
TN                0
TG                0
TR                0
UP                0
UT                0
WB                0
UN                0
Name: 2, dtype: object

## Linear regression
![title](https://files.realpython.com/media/fig-lin-reg.a506035b654a.png)

In [9]:
import numpy as np
from sklearn.linear_model import LinearRegression

x_list = [i for i in range(200)]
y_list = [i*3 for i in x_list]

print('X: ',x_list[:15])
print('Y: ',y_list[:15])

x = np.array(x_list).reshape((-1, 1))
y = np.array(y_list)

X:  [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14]
Y:  [0, 3, 6, 9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42]

In [10]:
model = LinearRegression()
model.fit(x, y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)